# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99a3cf3773a3097af8301c515dc4d9e08fb348ea275e8c83462d5a1d4cfddb6c7f359347c6e7c6e51f5271b788b7c45849806998f20a6660cef8ab1dcace63c2

test:
  secret_key_base: 84c3d26413b22e0c158dc5291defb054b4c7583c4499a6d2a067c30e87c884756973821283ee23ccd9aa8305303c1ad5e94829a4dafc429b2458b2b3dcc4d119

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
